name: basic git-workflow

on:
  push:
    branches:
      - master

  pull_request:


jobs:
  test:
    name: basic test
    runs-on: ubuntu-latest

    steps:
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Wish Me
        run: echo "Hellow"
