name: New Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test wokflow
    runs-on: ubuntu-latest

    steps:
      - name: Setup Actions
        uses: actions/checkout@v3

      - name: Wish Me
        run: echo "Hii Nikhil"
